server {
    listen       80;
    listen  [::]:80;
    server_name  _;

    location /v1/ {
        proxy_pass  https://tzsj.elias.ink/v1/;
    }

    location /gis/ {
        alias /gis/;
        try_files $uri $uri/ /gis/index.html;
    }

    location / {
        root /dist;
        try_files $uri $uri/ /index.html;
    }
}