


server {
  listen 80;
  server_name thinkasany.com; 

   proxy_set_header Host $http_host;
   proxy_set_header Referer $http_referer;
   # 解决websocket中报failed: Error during WebSocket handshake: Unexpected response code: 400 
   proxy_http_version 1.1;    # Nginx在与Node后端通信时使用HTTP/1.1，这是WebSockets所必需的
   proxy_set_header Upgrade $http_upgrade; # 这两行告诉Nginx响应升级请求，当浏览器想要使用WebSocket时，该请求由HTTP启动
   proxy_set_header Connection "upgrade";
  access_log  /Users/thinkerwing/Desktop/access.log;

  error_log /Users/thinkerwing/Desktop/test.log;

  location =/ {
          proxy_pass http://127.0.0.1:8003;
  }


  location /gis/ {
      alias /Users/thinkerwing/Desktop/qyzw/investment-audit-web/gis/;
      index index.html index.htm;
      try_files $uri $uri/  /gis$uri =404;
  }

  location / {
          proxy_pass http://127.0.0.1:8003;
  }
}
